# Data Loading

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("ObesityDataSet.csv")
df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [3]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
df.tail()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [5]:
df.shape

(2111, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [7]:
df.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [8]:
df.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [9]:
df.describe(include="object")

,Gender,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,NObeyesdad
count,2111,2111,2111,2111,2111,2111,2111,2111,2111
unique,2,2,2,4,2,2,4,5,7
top,Male,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_I
freq,1068,1726,1866,1765,2067,2015,1401,1580,351

In [10]:
df.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [11]:
df["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [12]:
df["family_history_with_overweight"].unique()

array(['yes', 'no'], dtype=object)

In [13]:
df["FAVC"].unique()

array(['no', 'yes'], dtype=object)

In [14]:
df["CAEC"].unique()

array(['Sometimes', 'Frequently', 'Always', 'no'], dtype=object)

In [15]:
df["SMOKE"].unique()

array(['no', 'yes'], dtype=object)

In [16]:
df["SCC"].unique()

array(['no', 'yes'], dtype=object)

In [17]:
df["CALC"].unique()

array(['no', 'Sometimes', 'Frequently', 'Always'], dtype=object)

In [18]:
df["MTRANS"].unique()

array(['Public_Transportation', 'Walking', 'Automobile', 'Motorbike',
       'Bike'], dtype=object)

In [19]:
df["NObeyesdad"].unique()

array(['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II',
       'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_II',
       'Obesity_Type_III'], dtype=object)

# Label Encoding

In [20]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [21]:
df["Gender"] = encoder.fit_transform(df["Gender"])
df["family_history_with_overweight"] = encoder.fit_transform(df["family_history_with_overweight"])
df["FAVC"] = encoder.fit_transform(df["FAVC"])
df["CAEC"] = encoder.fit_transform(df["CAEC"])
df["SMOKE"] = encoder.fit_transform(df["SMOKE"])
df["SCC"] = encoder.fit_transform(df["SCC"])
df["CALC"] = encoder.fit_transform(df["CALC"])
df["MTRANS"] = encoder.fit_transform(df["MTRANS"])
df["NObeyesdad"] = encoder.fit_transform(df["NObeyesdad"])

In [22]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,1,0,2.0,3.0,2,0,2.0,0,0.0,1.0,3,3,1
1,0,21.0,1.52,56.0,1,0,3.0,3.0,2,1,3.0,1,3.0,0.0,2,3,1
2,1,23.0,1.80,77.0,1,0,2.0,3.0,2,0,2.0,0,2.0,1.0,1,3,1
3,1,27.0,1.80,87.0,0,0,3.0,3.0,2,0,2.0,0,2.0,0.0,1,4,5
4,1,22.0,1.78,89.8,0,0,2.0,1.0,2,0,2.0,0,0.0,0.0,2,3,6

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   int32
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   int32
 5   FAVC                            2111 non-null   int32
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   int32
 9   SMOKE                           2111 non-null   int32
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   int32
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   int32
 15  MTRANS                          2111 non-null   int32
 16  NObeyesdad                      2111 non-null   int32
dtypes: float64(8), int32(9)
memory usage: 206.3 KB

# Standard Scaler

In [24]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()

In [25]:
scaler.fit_transform(df)

array([[-1.01191369, -0.52212439, -0.87558934, ...,  1.4191716 ,
         0.50333674, -1.03279553],
       [-1.01191369, -0.52212439, -1.94759928, ..., -0.52115952,
         0.50333674, -1.03279553],
       [ 0.98822657, -0.20688898,  1.05402854, ..., -2.46149063,
         0.50333674, -1.03279553],
       ...,
       [-1.01191369, -0.28190933,  0.54167211, ..., -0.52115952,
         0.50333674,  0.50438287],
       [-1.01191369,  0.00777624,  0.40492652, ..., -0.52115952,
         0.50333674,  0.50438287],
       [-1.01191369, -0.10211908,  0.39834438, ..., -0.52115952,
         0.50333674,  0.50438287]])

# Data Split - train, test, valid

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X = df.drop(columns=["NObeyesdad"])
Y = df["NObeyesdad"]

In [28]:
X_train, X_temp, Y_train, Y_temp = train_test_split(X, Y, train_size=0.7)

In [29]:
X_valid, X_test, Y_valid, Y_test = train_test_split(X_temp, Y_temp, test_size=0.5)

# Model Training

## 1. Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [31]:
RF = RandomForestClassifier(n_estimators=100, random_state=42)

In [32]:
RF.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [33]:
Y_pred_rf = RF.predict(X_valid)

In [34]:
print(classification_report(Y_valid, Y_pred_rf))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92        40
           1       0.77      0.86      0.81        42
           2       0.97      0.95      0.96        60
           3       1.00      0.97      0.99        38
           4       0.98      1.00      0.99        45
           5       0.91      0.91      0.91        43
           6       0.94      0.90      0.92        49

    accuracy                           0.93       317
   macro avg       0.93      0.93      0.93       317
weighted avg       0.93      0.93      0.93       317

## 2. SVM

In [70]:
from sklearn.svm import SVC

In [71]:
SVM = SVC(kernel="linear")

In [55]:
SVM.fit(X_train, Y_train)

SVC(kernel='linear')

In [56]:
Y_pred_svm = SVM.predict(X_valid)

In [57]:
print(classification_report(Y_valid, Y_pred_svm))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89        40
           1       0.79      0.62      0.69        42
           2       0.87      0.88      0.88        60
           3       0.93      0.97      0.95        38
           4       0.98      1.00      0.99        45
           5       0.66      0.86      0.75        43
           6       0.86      0.63      0.73        49

    accuracy                           0.84       317
   macro avg       0.85      0.85      0.84       317
weighted avg       0.85      0.84      0.84       317

### Grid Search

In [68]:
from sklearn.model_selection import GridSearchCV

In [72]:
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
            'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
            'kernel': ['linear']} 

grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)

In [76]:
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1, kernel=linear;, score=0.895 total time=   0.1s
[CV 2/5] END .......C=1, gamma=1, kernel=linear;, score=0.868 total time=   0.1s
[CV 3/5] END .......C=1, gamma=1, kernel=linear;, score=0.871 total time=   0.1s
[CV 4/5] END .......C=1, gamma=1, kernel=linear;, score=0.861 total time=   0.1s
[CV 5/5] END .......C=1, gamma=1, kernel=linear;, score=0.858 total time=   0.1s
[CV 1/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.895 total time=   0.1s
[CV 2/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.868 total time=   0.1s
[CV 3/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.871 total time=   0.1s
[CV 4/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.861 total time=   0.1s
[CV 5/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.858 total time=   0.1s
[CV 1/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.895 total time=   0.1s
[CV 2/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.868 total time=   0.1s
[CV 3/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.871 total time=   0.1s
[CV 4/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.861 total time=   0.1s
[CV 5/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.858 total time=   0.1s
[CV 1/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.895 total time=   0.1s
[CV 2/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.868 total time=   0.1s
[CV 3/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.871 total time=   0.1s
[CV 4/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.861 total time=   0.1s
[CV 5/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.858 total time=   0.1s
[CV 1/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.895 total time=   0.1s
[CV 2/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.868 total time=   0.1s
[CV 3/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.871 total time=   0.1s
[CV 4/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.861 total time=   0.1s
[CV 5/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.858 total time=   0.1s
[CV 1/5] END ......C=10, gamma=1, kernel=linear;, score=0.953 total time=   0.5s
[CV 2/5] END ......C=10, gamma=1, kernel=linear;, score=0.943 total time=   0.8s
[CV 3/5] END ......C=10, gamma=1, kernel=linear;, score=0.932 total time=   0.9s
[CV 4/5] END ......C=10, gamma=1, kernel=linear;, score=0.919 total time=   0.7s
[CV 5/5] END ......C=10, gamma=1, kernel=linear;, score=0.922 total time=   0.7s
[CV 1/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.953 total time=   0.5s
[CV 2/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.943 total time=   0.8s
[CV 3/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.932 total time=   0.8s
[CV 4/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.919 total time=   0.7s
[CV 5/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.922 total time=   0.6s
[CV 1/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.953 total time=   0.5s
[CV 2/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.943 total time=   0.8s
[CV 3/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.932 total time=   0.9s
[CV 4/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.919 total time=   0.7s
[CV 5/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.922 total time=   0.7s
[CV 1/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.953 total time=   0.5s
[CV 2/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.943 total time=   0.8s
[CV 3/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.932 total time=   0.8s
[CV 4/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.919 total time=   0.7s
[CV 5/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.922 total time=   0.7s
[CV 1/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.953 total time=   0.5s
[CV 2/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.943 total time=   0.8s
[CV 3/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.932 total time=   0.8s
[CV 4/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.919 total time=   0.7s
[CV 5/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.922 total time=   0.7s
[CV 1/5] END .....C=100, gamma=1, kernel=linear;, score=0.973 total time=   2.5s
[CV 2/5] END .....C=100, gamma=1, kernel=linear;, score=0.963 total time=   3.5s
[CV 3/5] END .....C=100, gamma=1, kernel=linear;, score=0.956 total time=   4.1s
[CV 4/5] END .....C=100, gamma=1, kernel=linear;, score=0.942 total time=   3.6s
[CV 5/5] END .....C=100, gamma=1, kernel=linear;, score=0.949 total time=   3.7s
[CV 1/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.973 total time=   2.6s
[CV 2/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.963 total time=   3.7s
[CV 3/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.956 total time=   4.0s
[CV 4/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.942 total time=   3.5s
[CV 5/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.949 total time=   3.4s
[CV 1/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.973 total time=   2.5s
[CV 2/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.963 total time=   3.3s
[CV 3/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.956 total time=   4.0s
[CV 4/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.942 total time=   3.3s
[CV 5/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.949 total time=   3.4s
[CV 1/5] END .C=100, gamma=0.001, kernel=linear;, score=0.973 total time=   2.5s
[CV 2/5] END .C=100, gamma=0.001, kernel=linear;, score=0.963 total time=   3.3s
[CV 3/5] END .C=100, gamma=0.001, kernel=linear;, score=0.956 total time=   4.0s
[CV 4/5] END .C=100, gamma=0.001, kernel=linear;, score=0.942 total time=   3.3s
[CV 5/5] END .C=100, gamma=0.001, kernel=linear;, score=0.949 total time=   3.2s
[CV 1/5] END C=100, gamma=0.0001, kernel=linear;, score=0.973 total time=   2.6s
[CV 2/5] END C=100, gamma=0.0001, kernel=linear;, score=0.963 total time=   3.3s
[CV 3/5] END C=100, gamma=0.0001, kernel=linear;, score=0.956 total time=   4.7s
[CV 4/5] END C=100, gamma=0.0001, kernel=linear;, score=0.942 total time=   3.8s
[CV 5/5] END C=100, gamma=0.0001, kernel=linear;, score=0.949 total time=   3.7s
[CV 1/5] END ....C=1000, gamma=1, kernel=linear;, score=0.973 total time=   9.3s
[CV 2/5] END ....C=1000, gamma=1, kernel=linear;, score=0.963 total time=   7.3s
[CV 3/5] END ....C=1000, gamma=1, kernel=linear;, score=0.953 total time=  23.7s
[CV 4/5] END ....C=1000, gamma=1, kernel=linear;, score=0.936 total time=   8.1s
[CV 5/5] END ....C=1000, gamma=1, kernel=linear;, score=0.949 total time=  13.9s
[CV 1/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.973 total time=   9.2s
[CV 2/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.963 total time=   7.9s
[CV 3/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.953 total time=  22.7s
[CV 4/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.936 total time=   5.4s
[CV 5/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.949 total time=   8.8s
[CV 1/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.973 total time=   6.7s
[CV 2/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.963 total time=   4.5s
[CV 3/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.953 total time=  15.9s
[CV 4/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.936 total time=   4.7s
[CV 5/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.949 total time=   8.2s
[CV 1/5] END C=1000, gamma=0.001, kernel=linear;, score=0.973 total time=   6.1s
[CV 2/5] END C=1000, gamma=0.001, kernel=linear;, score=0.963 total time=   5.0s
[CV 3/5] END C=1000, gamma=0.001, kernel=linear;, score=0.953 total time=  16.1s
[CV 4/5] END C=1000, gamma=0.001, kernel=linear;, score=0.936 total time=   5.5s
[CV 5/5] END C=1000, gamma=0.001, kernel=linear;, score=0.949 total time=   7.9s
[CV 1/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.973 total time=   8.4s
[CV 2/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.963 total time=   5.9s
[CV 3/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.953 total time=  16.5s
[CV 4/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.936 total time=   5.2s
[CV 5/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.949 total time=   8.6s

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [77]:
print(grid.best_params_)

{'C': 100, 'gamma': 1, 'kernel': 'linear'}

In [78]:
print(grid.best_estimator_)

SVC(C=100, gamma=1, kernel='linear')

In [79]:
Y_pred_grid = grid.predict(X_valid)

In [80]:
print(classification_report(Y_valid, Y_pred_grid))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96        40
           1       0.97      0.90      0.94        42
           2       0.95      0.95      0.95        60
           3       0.97      0.97      0.97        38
           4       0.98      1.00      0.99        45
           5       0.83      0.93      0.88        43
           6       0.98      0.90      0.94        49

    accuracy                           0.95       317
   macro avg       0.95      0.95      0.95       317
weighted avg       0.95      0.95      0.95       317

# 3. Extra Tree Classifier

In [58]:
from sklearn.ensemble import ExtraTreesClassifier

In [59]:
ETC = ExtraTreesClassifier(n_estimators=100)

In [60]:
ETC.fit(X_train, Y_train)

ExtraTreesClassifier()

In [61]:
Y_pred_etc = ETC.predict(X_valid)

In [62]:
print(classification_report(Y_valid, Y_pred_etc))

              precision    recall  f1-score   support

           0       0.97      0.90      0.94        40
           1       0.72      0.90      0.80        42
           2       0.94      0.97      0.95        60
           3       1.00      0.97      0.99        38
           4       1.00      1.00      1.00        45
           5       0.90      0.86      0.88        43
           6       0.98      0.84      0.90        49

    accuracy                           0.92       317
   macro avg       0.93      0.92      0.92       317
weighted avg       0.93      0.92      0.92       317

# Ensemble Model

In [63]:
from sklearn.ensemble import VotingClassifier

In [64]:
ensemble_model = VotingClassifier(estimators=[
    ('RF', RF),
    ('ETC', ETC),
    ('SVM', SVM)
], voting='hard')

In [65]:
ensemble_model.fit(X_train, Y_train)

VotingClassifier(estimators=[('RF', RandomForestClassifier(random_state=42)),
                             ('ETC', ExtraTreesClassifier()),
                             ('SVM', SVC(kernel='linear'))])

In [66]:
Y_pred_ensemble = ensemble_model.predict(X_valid)

In [67]:
print(classification_report(Y_valid, Y_pred_ensemble))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92        40
           1       0.73      0.88      0.80        42
           2       0.97      0.97      0.97        60
           3       1.00      0.97      0.99        38
           4       0.98      1.00      0.99        45
           5       0.93      0.86      0.89        43
           6       0.96      0.88      0.91        49

    accuracy                           0.92       317
   macro avg       0.93      0.92      0.92       317
weighted avg       0.93      0.92      0.93       317

In [81]:
ensemble_model2 = VotingClassifier(estimators=[
    ('RF', RF),
    ('ETC', ETC),
    ('grid', grid)
], voting='hard')

In [82]:
ensemble_model2.fit(X_train, Y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.855 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.818 total time=   0.0s
[CV 3/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.824 total time=   0.0s
[CV 4/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.814 total time=   0.0s
[CV 5/5] END C=0.1, gamma=0.0001, kernel=linear;, score=0.817 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1, kernel=linear;, score=0.895 total time=   0.0s
[CV 2/5] END .......C=1, gamma=1, kernel=linear;, score=0.868 total time=   0.0s
[CV 3/5] END .......C=1, gamma=1, kernel=linear;, score=0.871 total time=   0.0s
[CV 4/5] END .......C=1, gamma=1, kernel=linear;, score=0.861 total time=   0.0s
[CV 5/5] END .......C=1, gamma=1, kernel=linear;, score=0.858 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.895 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.868 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.871 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.861 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.858 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.895 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.868 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.871 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.861 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.858 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.895 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.868 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.871 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.861 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.858 total time=   0.0s
[CV 1/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.895 total time=   0.0s
[CV 2/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.868 total time=   0.0s
[CV 3/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.871 total time=   0.0s
[CV 4/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.861 total time=   0.0s
[CV 5/5] END ..C=1, gamma=0.0001, kernel=linear;, score=0.858 total time=   0.0s
[CV 1/5] END ......C=10, gamma=1, kernel=linear;, score=0.953 total time=   0.3s
[CV 2/5] END ......C=10, gamma=1, kernel=linear;, score=0.943 total time=   0.6s
[CV 3/5] END ......C=10, gamma=1, kernel=linear;, score=0.932 total time=   0.5s
[CV 4/5] END ......C=10, gamma=1, kernel=linear;, score=0.919 total time=   0.4s
[CV 5/5] END ......C=10, gamma=1, kernel=linear;, score=0.922 total time=   0.4s
[CV 1/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.953 total time=   0.1s
[CV 2/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.943 total time=   0.6s
[CV 3/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.932 total time=   0.6s
[CV 4/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.919 total time=   0.4s
[CV 5/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.922 total time=   0.3s
[CV 1/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.953 total time=   0.3s
[CV 2/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.943 total time=   0.6s
[CV 3/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.932 total time=   0.6s
[CV 4/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.919 total time=   0.4s
[CV 5/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.922 total time=   0.4s
[CV 1/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.953 total time=   0.3s
[CV 2/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.943 total time=   0.6s
[CV 3/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.932 total time=   0.6s
[CV 4/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.919 total time=   0.5s
[CV 5/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.922 total time=   0.4s
[CV 1/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.953 total time=   0.3s
[CV 2/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.943 total time=   0.5s
[CV 3/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.932 total time=   0.6s
[CV 4/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.919 total time=   0.4s
[CV 5/5] END .C=10, gamma=0.0001, kernel=linear;, score=0.922 total time=   0.5s
[CV 1/5] END .....C=100, gamma=1, kernel=linear;, score=0.973 total time=   1.7s
[CV 2/5] END .....C=100, gamma=1, kernel=linear;, score=0.963 total time=   2.1s
[CV 3/5] END .....C=100, gamma=1, kernel=linear;, score=0.956 total time=   2.8s
[CV 4/5] END .....C=100, gamma=1, kernel=linear;, score=0.942 total time=   2.2s
[CV 5/5] END .....C=100, gamma=1, kernel=linear;, score=0.949 total time=   2.1s
[CV 1/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.973 total time=   1.7s
[CV 2/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.963 total time=   2.3s
[CV 3/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.956 total time=   2.7s
[CV 4/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.942 total time=   2.2s
[CV 5/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.949 total time=   2.3s
[CV 1/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.973 total time=   1.8s
[CV 2/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.963 total time=   2.3s
[CV 3/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.956 total time=   2.8s
[CV 4/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.942 total time=   2.4s
[CV 5/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.949 total time=   2.0s
[CV 1/5] END .C=100, gamma=0.001, kernel=linear;, score=0.973 total time=   1.7s
[CV 2/5] END .C=100, gamma=0.001, kernel=linear;, score=0.963 total time=   2.1s
[CV 3/5] END .C=100, gamma=0.001, kernel=linear;, score=0.956 total time=   2.8s
[CV 4/5] END .C=100, gamma=0.001, kernel=linear;, score=0.942 total time=   2.2s
[CV 5/5] END .C=100, gamma=0.001, kernel=linear;, score=0.949 total time=   2.2s
[CV 1/5] END C=100, gamma=0.0001, kernel=linear;, score=0.973 total time=   1.6s
[CV 2/5] END C=100, gamma=0.0001, kernel=linear;, score=0.963 total time=   2.1s
[CV 3/5] END C=100, gamma=0.0001, kernel=linear;, score=0.956 total time=   2.7s
[CV 4/5] END C=100, gamma=0.0001, kernel=linear;, score=0.942 total time=   2.2s
[CV 5/5] END C=100, gamma=0.0001, kernel=linear;, score=0.949 total time=   2.3s
[CV 1/5] END ....C=1000, gamma=1, kernel=linear;, score=0.973 total time=   5.6s
[CV 2/5] END ....C=1000, gamma=1, kernel=linear;, score=0.963 total time=   5.1s
[CV 3/5] END ....C=1000, gamma=1, kernel=linear;, score=0.953 total time=  15.5s
[CV 4/5] END ....C=1000, gamma=1, kernel=linear;, score=0.936 total time=   5.0s
[CV 5/5] END ....C=1000, gamma=1, kernel=linear;, score=0.949 total time=   8.2s
[CV 1/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.973 total time=   6.2s
[CV 2/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.963 total time=   5.0s
[CV 3/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.953 total time=  15.9s
[CV 4/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.936 total time=   5.3s
[CV 5/5] END ..C=1000, gamma=0.1, kernel=linear;, score=0.949 total time=   7.7s
[CV 1/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.973 total time=   5.8s
[CV 2/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.963 total time=   5.1s
[CV 3/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.953 total time=  16.4s
[CV 4/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.936 total time=   5.4s
[CV 5/5] END .C=1000, gamma=0.01, kernel=linear;, score=0.949 total time=   8.1s
[CV 1/5] END C=1000, gamma=0.001, kernel=linear;, score=0.973 total time=   6.2s
[CV 2/5] END C=1000, gamma=0.001, kernel=linear;, score=0.963 total time=   5.1s
[CV 3/5] END C=1000, gamma=0.001, kernel=linear;, score=0.953 total time=  15.6s
[CV 4/5] END C=1000, gamma=0.001, kernel=linear;, score=0.936 total time=   5.0s
[CV 5/5] END C=1000, gamma=0.001, kernel=linear;, score=0.949 total time=   8.4s
[CV 1/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.973 total time=   6.0s
[CV 2/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.963 total time=   7.9s
[CV 3/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.953 total time=  23.9s
[CV 4/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.936 total time=   7.8s
[CV 5/5] END C=1000, gamma=0.0001, kernel=linear;, score=0.949 total time=  12.8s

VotingClassifier(estimators=[('RF', RandomForestClassifier(random_state=42)),
                             ('ETC', ExtraTreesClassifier()),
                             ('grid',
                              GridSearchCV(estimator=SVC(),
                                           param_grid={'C': [0.1, 1, 10, 100,
                                                             1000],
                                                       'gamma': [1, 0.1, 0.01,
                                                                 0.001,
                                                                 0.0001],
                                                       'kernel': ['linear']},
                                           verbose=3))])

In [83]:
Y_pred_ensemble2 = ensemble_model2.predict(X_valid)

In [84]:
print(classification_report(Y_valid, Y_pred_ensemble2))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        40
           1       0.78      0.93      0.85        42
           2       0.97      0.97      0.97        60
           3       1.00      0.97      0.99        38
           4       0.98      1.00      0.99        45
           5       0.97      0.91      0.94        43
           6       0.98      0.90      0.94        49

    accuracy                           0.94       317
   macro avg       0.95      0.94      0.94       317
weighted avg       0.95      0.94      0.94       317