## 1. Data Preprocessing and Splitting
Load the dataset and preprocess it. Handle any missing or categorical data using appropriate methods (e.g., Label Encoding, Standard Scaler). Split the dataset into a training set (70%), a validation set (15%), and a test set (15%)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("Train.csv")
train

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
8063,464018,Male,No,22,No,NaN,0.0,Low,7.0,Cat_1,D
8064,464685,Male,No,35,No,Executive,3.0,Low,4.0,Cat_4,D
8065,465406,Female,No,33,Yes,Healthcare,1.0,Low,1.0,Cat_6,D
8066,467299,Female,No,27,Yes,Healthcare,1.0,Low,4.0,Cat_6,B
8067,461879,Male,Yes,37,Yes,Executive,0.0,Average,3.0,Cat_4,B

In [3]:
test = pd.read_csv("Test.csv")
test

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,Female,Yes,36,Yes,Engineer,0.0,Low,1.0,Cat_6,B
1,458994,Male,Yes,37,Yes,Healthcare,8.0,Average,4.0,Cat_6,A
2,458996,Female,Yes,69,No,NaN,0.0,Low,1.0,Cat_6,A
3,459000,Male,Yes,59,No,Executive,11.0,High,2.0,Cat_6,B
4,459001,Female,No,19,No,Marketing,NaN,Low,4.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,Male,No,29,No,Healthcare,9.0,Low,4.0,Cat_6,B
2623,467958,Female,No,35,Yes,Doctor,1.0,Low,1.0,Cat_6,A
2624,467960,Female,No,53,Yes,Entertainment,NaN,Low,2.0,Cat_6,C
2625,467961,Male,Yes,47,Yes,Executive,1.0,High,5.0,Cat_4,C
2626,467968,Female,No,43,Yes,Healthcare,9.0,Low,3.0,Cat_7,A

In [4]:
df = pd.concat([train, test])
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,Male,No,29,No,Healthcare,9.0,Low,4.0,Cat_6,B
2623,467958,Female,No,35,Yes,Doctor,1.0,Low,1.0,Cat_6,A
2624,467960,Female,No,53,Yes,Entertainment,NaN,Low,2.0,Cat_6,C
2625,467961,Male,Yes,47,Yes,Executive,1.0,High,5.0,Cat_4,C
2626,467968,Female,No,43,Yes,Healthcare,9.0,Low,3.0,Cat_7,A

In [5]:
df.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A

In [6]:
df.tail()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
2622,467954,Male,No,29,No,Healthcare,9.0,Low,4.0,Cat_6,B
2623,467958,Female,No,35,Yes,Doctor,1.0,Low,1.0,Cat_6,A
2624,467960,Female,No,53,Yes,Entertainment,NaN,Low,2.0,Cat_6,C
2625,467961,Male,Yes,47,Yes,Executive,1.0,High,5.0,Cat_4,C
2626,467968,Female,No,43,Yes,Healthcare,9.0,Low,3.0,Cat_7,A

In [7]:
df.shape

(10695, 11)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10695 entries, 0 to 2626
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               10695 non-null  int64
 1   Gender           10695 non-null  object
 2   Ever_Married     10505 non-null  object
 3   Age              10695 non-null  int64
 4   Graduated        10593 non-null  object
 5   Profession       10533 non-null  object
 6   Work_Experience  9597 non-null   float64
 7   Spending_Score   10695 non-null  object
 8   Family_Size      10247 non-null  float64
 9   Var_1            10587 non-null  object
 10  Segmentation     10695 non-null  object
dtypes: float64(2), int64(2), object(7)
memory usage: 1002.7+ KB

In [9]:
df.describe()

                  ID           Age  Work_Experience   Family_Size
count   10695.000000  10695.000000      9597.000000  10247.000000
mean   463468.088640     43.511828         2.619777      2.844052
std      2600.966411     16.774158         3.390790      1.536427
min    458982.000000     18.000000         0.000000      1.000000
25%    461220.500000     30.000000         0.000000      2.000000
50%    463451.000000     41.000000         1.000000      3.000000
75%    465733.500000     53.000000         4.000000      4.000000
max    467974.000000     89.000000        14.000000      9.000000

In [10]:
df.describe(include="object")

,Gender,Ever_Married,Graduated,Profession,Spending_Score,Var_1,Segmentation
count,10695,10505,10593,10533,10695,10587,10695
unique,2,2,2,9,3,7,4
top,Male,Yes,Yes,Artist,Low,Cat_6,D
freq,5841,6163,6570,3318,6494,6910,3027

In [11]:
df.columns

Index(['ID', 'Gender', 'Ever_Married', 'Age', 'Graduated', 'Profession',
       'Work_Experience', 'Spending_Score', 'Family_Size', 'Var_1',
       'Segmentation'],
      dtype='object')

In [12]:
df.isnull().sum()

ID                    0
Gender                0
Ever_Married        190
Age                   0
Graduated           102
Profession          162
Work_Experience    1098
Spending_Score        0
Family_Size         448
Var_1               108
Segmentation          0
dtype: int64

In [13]:
df_cleaned = df.dropna()

In [14]:
df_cleaned.isnull().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
Segmentation       0
dtype: int64

In [ ]:
df_cleaned.shape

### Label Encoding

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [16]:
df_cleaned["Gender"] = encoder.fit_transform(df_cleaned["Gender"])
df_cleaned["Ever_Married"] = encoder.fit_transform(df_cleaned["Ever_Married"])
df_cleaned["Graduated"] = encoder.fit_transform(df_cleaned["Graduated"])
df_cleaned["Profession"] = encoder.fit_transform(df_cleaned["Profession"])
df_cleaned["Spending_Score"] = encoder.fit_transform(df_cleaned["Spending_Score"])
df_cleaned["Var_1"] = encoder.fit_transform(df_cleaned["Var_1"])
df_cleaned["Segmentation"] = encoder.fit_transform(df_cleaned["Segmentation"])

C:\Users\nensi\AppData\Local\Temp\ipykernel_11464\3788248170.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Gender"] = encoder.fit_transform(df_cleaned["Gender"])
C:\Users\nensi\AppData\Local\Temp\ipykernel_11464\3788248170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Ever_Married"] = encoder.fit_transform(df_cleaned["Ever_Married"])
C:\Users\nensi\AppData\Local\Temp\ipykernel_11464\3788248170.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Graduated"] = encoder.fit_transform(df_cleaned["Graduated"])
C:\Users\nensi\AppData\Local\Temp\ipykernel_11464\3788248170.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Profession"] = encoder.fit_transform(df_cleaned["Profession"])
C:\Users\nensi\AppData\Local\Temp\ipykernel_11464\3788248170.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Spending_Score"] = encoder.fit_transform(df_cleaned["Spending_Score"])
C:\Users\nensi\AppData\Local\Temp\ipykernel_11464\3788248170.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Var_1"] = encoder.fit_transform(df_cleaned["Var_1"])
C:\Users\nensi\AppData\Local\Temp\ipykernel_11464\3788248170.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Segmentation"] = encoder.fit_transform(df_cleaned["Segmentation"])

In [17]:
df_cleaned.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,1,0,22,0,5,1.0,2,4.0,3,3
2,466315,0,1,67,1,2,1.0,2,1.0,5,1
3,461735,1,1,67,1,7,0.0,1,2.0,5,1
5,461319,1,1,56,0,0,0.0,0,2.0,5,2
6,460156,1,0,32,1,5,1.0,2,3.0,5,2

### Standard Scaler

In [18]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()

In [19]:
scaler.fit_transform(df_cleaned)

array([[-0.27415205,  0.90235013, -1.20319678, ...,  0.75564136,
        -0.83736547,  1.29246432],
       [ 1.08883342, -1.10821727,  0.83111925, ..., -1.19880222,
         0.58729472, -0.4518532 ],
       [-0.69167811,  0.90235013,  0.83111925, ..., -0.54732103,
         0.58729472, -0.4518532 ],
       ...,
       [ 1.72756278, -1.10821727, -1.20319678, ..., -1.19880222,
         0.58729472, -1.32401196],
       [ 1.72872905,  0.90235013,  0.83111925, ...,  1.40712255,
        -0.83736547,  0.42030556],
       [ 1.73145036, -1.10821727, -1.20319678, ...,  0.10416016,
         1.29962482, -1.32401196]])

### Data Split - train, test, valid

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X = df_cleaned.drop(columns=["Segmentation"])
Y = df_cleaned["Segmentation"]

In [22]:
X_train, X_temp, Y_train, Y_temp = train_test_split(X, Y, train_size=0.7)

In [23]:
X_valid, X_test, Y_valid, Y_test = train_test_split(X_temp, Y_temp, test_size=0.5)

# 2. Model Training
Train three classifiers: a Random Forest Classifier, an Extra Trees Classifier, and a Support Vector Machine (SVM) classifier on the preprocessed training data.

# 3. Model Evaluation
Evaluate the performance of the trained models (Random Forest, Extra Trees, and SVM) on the validation set. Report the accuracy scores for each classifier.

## 1. Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [25]:
RF = RandomForestClassifier(n_estimators=100, random_state=42)

In [26]:
RF.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [27]:
Y_pred_rf = RF.predict(X_valid)

In [28]:
print(classification_report(Y_valid, Y_pred_rf))

              precision    recall  f1-score   support

           0       0.38      0.40      0.39       349
           1       0.39      0.29      0.33       307
           2       0.47      0.46      0.46       322
           3       0.49      0.59      0.54       345

    accuracy                           0.44      1323
   macro avg       0.43      0.43      0.43      1323
weighted avg       0.43      0.44      0.43      1323

## 2. SVM

In [40]:
from sklearn.svm import SVC

In [41]:
SVM = SVC(kernel="linear")

In [ ]:
SVM.fit(X_train, Y_train)

In [ ]:
Y_pred_svm = SVM.predict(X_valid)

In [ ]:
print(classification_report(Y_valid, Y_pred_svm))

## 3. Extra Tree Classifier

In [29]:
from sklearn.ensemble import ExtraTreesClassifier

In [30]:
ETC = ExtraTreesClassifier(n_estimators=100)

In [31]:
ETC.fit(X_train, Y_train)

ExtraTreesClassifier()

In [32]:
Y_pred_etc = ETC.predict(X_valid)

In [33]:
print(classification_report(Y_valid, Y_pred_etc))

              precision    recall  f1-score   support

           0       0.38      0.40      0.39       349
           1       0.35      0.28      0.31       307
           2       0.42      0.42      0.42       322
           3       0.51      0.57      0.54       345

    accuracy                           0.42      1323
   macro avg       0.42      0.42      0.42      1323
weighted avg       0.42      0.42      0.42      1323

## 4. Gradient Boosting

In [34]:
from sklearn.ensemble import GradientBoostingClassifier

In [35]:
GBC = GradientBoostingClassifier(n_estimators=300,
                                 learning_rate=0.05,
                                 random_state=100,
                                 max_features=5)

In [36]:
GBC.fit(X_train, Y_train)

GradientBoostingClassifier(learning_rate=0.05, max_features=5, n_estimators=300,
                           random_state=100)

In [37]:
Y_pred_gbc = GBC.predict(X_valid)

In [38]:
print(classification_report(Y_valid, Y_pred_gbc))

              precision    recall  f1-score   support

           0       0.41      0.42      0.41       349
           1       0.37      0.28      0.32       307
           2       0.52      0.51      0.51       322
           3       0.52      0.63      0.57       345

    accuracy                           0.46      1323
   macro avg       0.46      0.46      0.46      1323
weighted avg       0.46      0.46      0.46      1323

# 4. Ensemble Model
Combine the three classifiers into an Ensemble model using hard voting. Train the ensemble on the training data and evaluate it on the validation set. Does the ensemble model outperform the individual classifiers on the validation set? What are the advantages of using an ensemble model?

In [39]:
from sklearn.ensemble import VotingClassifier

In [ ]:
ensemble_model = VotingClassifier(estimators=[
    ('RF', RF),
    ('ETC', ETC),
    ('SVM', SVM)
], voting='hard')

In [ ]:
ensemble_model.fit(X_train, Y_train)

In [ ]:
Y_pred_ensemble = ensemble_model.predict(X_valid)

In [ ]:
print(classification_report(Y_valid, Y_pred_ensemble))